using System.Text.RegularExpressions;
using Orleans.Lattice.Testing.Hygiene;

namespace Orleans.Lattice.Tests.Hygiene;

/// <summary>
/// The trailer guard: a banned attribution trailer must be caught wherever it
/// comes from, including the one place it does not exist yet when the guard
/// runs.
/// <para>
/// The guard's original arm scans the pull request's own commit messages, and
/// it is correct at that. It is also structurally blind to the way a banned
/// trailer has actually reached <c>main</c> here. GitHub composes the squash
/// commit message itself when no explicit body is supplied, and appends a
/// <c>Co-authored-by:</c> line for every distinct commit-author identity on the
/// pull request beyond the one it makes the author. Every commit message is
/// clean, the guard passes honestly, and the trailer is generated afterwards -
/// at the instant of the merge, where no pre-merge check can read it.
/// </para>
/// <para>
/// The general form is worth stating because it recurs well beyond trailers:
/// an artefact generated BY an action cannot be validated by a check that runs
/// BEFORE that action, so the gate has to move to the cause. The cause here is
/// fully decidable while the pull request is open - a pull request whose
/// commits all carry one author identity gives GitHub nothing to attribute -
/// so the second arm gates the identity COUNT rather than reaching for the
/// trailer.
/// </para>
/// <para>
/// The last assertion is the one that matters most and looks the least like a
/// test. The guard's behavioural coverage lives in
/// <c>trailer-guard-selftest.py</c>, which extracts the guard from
/// <c>ci.yml</c> unmodified and drives every arm against real git
/// repositories. A self-test that is not invoked is indistinguishable from a
/// clean guard - it reports nothing either way - so the wiring that invokes it
/// has to be held in place by something outside the workflow it is wiring.
/// </para>
/// </summary>
[TestFixture]
public sealed class CiTrailerGuardTests
{
    private const string WorkflowPath = ".github/workflows/ci.yml";
    private const string SelfTestPath = ".github/workflows/trailer-guard-selftest.py";
    private const string GuardStep = "Guard - branch name and commit trailers";

    /// <summary>
    /// The written-trailer arm must keep reading the full message of each of
    /// the pull request's own commits.
    /// </summary>
    [Test]
    public void The_trailer_guard_scans_the_pull_requests_own_commit_messages()
    {
        var step = Step(GuardStep);

        Assert.That(step, Does.Contain("Co-authored-by").And.Contain("Copilot-Session"),
            $"expected the '{GuardStep}' step in {WorkflowPath} to enumerate the banned "
            + "trailers; this fixture found the step but not the alternation, so every "
            + "assertion below would have been asserted against the wrong text");

        Assert.That(step, Does.Contain("rev-list"),
            $"the '{GuardStep}' step in {WorkflowPath} must enumerate the pull request's "
            + "own commits rather than a fixed count back from HEAD.");

        Assert.That(step, Does.Contain("BASE_SHA").And.Contain("HEAD_SHA"),
            $"the '{GuardStep}' step in {WorkflowPath} must address its commit range with "
            + "the event's base and head shas. On a pull_request event HEAD is the "
            + "synthetic merge commit, so a range anchored on HEAD would scan the base's "
            + "settled history or miss the commits this pull request adds.");

        Assert.That(step, Does.Contain("--format='%B'"),
            $"the '{GuardStep}' step in {WorkflowPath} must read the FULL commit message. "
            + "A trailer sits in the commit BODY by definition, so a subject-only read "
            + "would scan past every one of them while still reporting a commit count "
            + "that looks like work.");
    }

    /// <summary>
    /// The arm that gates the trailer GitHub manufactures at squash time. It
    /// cannot read that trailer - nothing can, before the merge - so it gates
    /// the author-identity count that causes it.
    /// </summary>
    [Test]
    public void The_trailer_guard_gates_the_squash_time_author_identity_count()
    {
        var step = Step(GuardStep);

        Assert.That(step, Does.Contain("identity_count"),
            $"the '{GuardStep}' step in {WorkflowPath} must gate the number of distinct "
            + "commit-author identities on the pull request. Without it the guard is "
            + "blind to the only way a banned trailer has actually reached the base "
            + "branch: GitHub composes one at squash time from those identities, long "
            + "after every arm that reads text has passed honestly.");

        Assert.That(step, Does.Contain("--format='%ae'"),
            $"the '{GuardStep}' step in {WorkflowPath} must dedupe author identities on "
            + "the EMAIL. The email is the identity GitHub attributes on, and the case "
            + "this arm exists to catch - one person committing under two accounts - "
            + "always differs there and need not differ in the display name.");

        Assert.That(step, Does.Match(@"identity_count.*-gt 1"),
            $"the '{GuardStep}' step in {WorkflowPath} must fail on MORE THAN ONE "
            + "identity, not on some larger number. One identity is the only count "
            + "that makes GitHub compose no trailer at all.");
    }

    /// <summary>
    /// An unread commit population must fail, not pass. It is otherwise
    /// indistinguishable in the result from a clean one.
    /// </summary>
    [Test]
    public void The_trailer_guard_fails_when_it_reads_no_commits()
    {
        var step = Step(GuardStep);

        Assert.That(step, Does.Match(@"identity_count.*-eq 0"),
            $"the '{GuardStep}' step in {WorkflowPath} must fail when its commit range "
            + "resolves to zero commits. Every pull request adds at least one, so an "
            + "empty range is a broken range - and both arms read that same range, so a "
            + "broken one reports exactly what a compliant pull request reports.");

        Assert.That(step, Does.Contain("zero commits"),
            $"the '{GuardStep}' step in {WorkflowPath} must say that the range resolved "
            + "to zero commits when it does. A non-vacuity failure that reads like an "
            + "ordinary violation sends the author to fix a compliant pull request.");
    }

    /// <summary>
    /// The guard's behavioural self-test must be invoked by the workflow. An
    /// uninvoked detector and a clean repository produce the same silence.
    /// </summary>
    [Test]
    public void The_trailer_guards_self_test_is_invoked_by_the_workflow()
    {
        var root = HygieneRepository.FindRepoRoot();

        Assert.That(File.Exists(Path.Combine(root, SelfTestPath.Replace('/', Path.DirectorySeparatorChar))),
            Is.True,
            $"expected {SelfTestPath} to exist; it is the only executable coverage of the "
            + $"'{GuardStep}' guard, which is an inline bash block with no importable "
            + "surface");

        var yaml = File.ReadAllText(Path.Combine(
            root, WorkflowPath.Replace('/', Path.DirectorySeparatorChar)));

        Assert.That(yaml, Does.Contain(SelfTestPath),
            $"{WorkflowPath} must invoke {SelfTestPath}. A self-test that is never run "
            + "reports nothing whether the guard is healthy or blind, so leaving it "
            + "unwired would remove the guard's only coverage without removing any green.");
    }

    /// <summary>
    /// Reads one workflow step by its <c>name:</c>, up to the next step at the
    /// same indentation. Fails rather than returning an empty string, because
    /// every assertion above would pass against one.
    /// </summary>
    private static string Step(string stepName)
    {
        var yaml = File.ReadAllText(Path.Combine(
            HygieneRepository.FindRepoRoot(),
            WorkflowPath.Replace('/', Path.DirectorySeparatorChar)));

        var start = Regex.Match(yaml, $@"^      - name: {Regex.Escape(stepName)}[ \t]*\r?$",
            RegexOptions.Multiline);

        Assert.That(start.Success, Is.True,
            $"expected a step named '{stepName}' in {WorkflowPath}. If it was renamed, this "
            + "fixture stopped guarding it and must be updated with it.");

        var rest = yaml[(start.Index + start.Length)..];
        var next = Regex.Match(rest, @"^      - (name|uses):", RegexOptions.Multiline);
        var block = next.Success ? rest[..next.Index] : rest;

        Assert.That(block.Trim(), Is.Not.Empty,
            $"the step named '{stepName}' in {WorkflowPath} has an empty body, so nothing "
            + "asserted about it means anything");

        return block;
    }
}
