using Orleans.Lattice.Primitives;

namespace Orleans.Lattice.Replication.Grains;

/// <summary>
/// Persistent state for <see cref="LatticeBootstrapCoordinatorGrain"/>.
/// Tracks the progress of an in-flight bootstrap so it can be resumed
/// after a silo crash or activation collection without re-fetching the
/// snapshot stream from the source's current as-of point. Mirrors the
/// shape of <c>TreeResizeState</c> in the core library.
/// <para>
/// On silo failover the keepalive reminder reactivates the grain on a
/// surviving silo; the work-pump resumes from <see cref="Phase"/> and
/// re-opens the snapshot stream with no upper bound
/// (<see cref="HybridLogicalClock.Zero"/>). The export treats its
/// <c>asOfHlc</c> as a strict upper bound and yields entries in
/// leaf-chain order, not HLC order, so re-opening at
/// <see cref="LastAppliedHlc"/> would exclude every not-yet-applied entry
/// stamped above the cursor. Receiver-side LWW reconciliation makes
/// re-applying the overlap with the prior partial drain a no-op.
/// </para>
/// </summary>
[GenerateSerializer]
[Alias(ReplicationTypeAliases.BootstrapCoordinatorState)]
internal sealed class BootstrapCoordinatorState
{
    /// <summary>
    /// Whether a bootstrap is currently in flight for this tree. The
    /// keepalive reminder reads this on every firing to decide whether
    /// to re-arm the phase timer or self-deactivate.
    /// </summary>
    [Id(0)] public bool InProgress { get; set; }

    /// <summary>
    /// The current observable phase of the bootstrap. Starts at
    /// <see cref="LatticeBootstrapState.Idle"/>; transitions through
    /// <see cref="LatticeBootstrapState.RequestingSnapshot"/>,
    /// <see cref="LatticeBootstrapState.ApplyingSnapshot"/>,
    /// <see cref="LatticeBootstrapState.IncrementalHandoff"/>, and
    /// terminates at <see cref="LatticeBootstrapState.LiveIncremental"/>.
    /// On any error transitions to <see cref="LatticeBootstrapState.Failed"/>.
    /// </summary>
    [Id(1)] public LatticeBootstrapState Phase { get; set; } = LatticeBootstrapState.Idle;

    /// <summary>
    /// The source cluster id supplied to
    /// <see cref="ILatticeBootstrapCoordinatorGrain.BootstrapAsync"/>.
    /// Used both as the origin tag for every applied entry (so transitive
    /// replication paths preserve the originating HLC) and to make the
    /// kickoff RPC idempotent - a second call with the same id while
    /// <see cref="InProgress"/> is a no-op; a different id throws.
    /// </summary>
    [Id(2)] public string SourceClusterId { get; set; } = "";

    /// <summary>
    /// Unique identifier for the in-flight bootstrap operation.
    /// Generated by <see cref="ILatticeBootstrapCoordinatorGrain.BootstrapAsync"/>
    /// when work begins. Reserved for diagnostics; not currently
    /// consulted on any code path.
    /// </summary>
    [Id(3)] public string OperationId { get; set; } = "";

    /// <summary>
    /// The highest <see cref="HybridLogicalClock"/> whose entry has
    /// been applied during the current bootstrap. Folded into the
    /// source-origin seal pinned at the incremental handoff. It is
    /// deliberately <b>not</b> passed to
    /// <see cref="ISnapshotProvider.ExportAsync"/> on a resume: the export
    /// treats that argument as a strict upper bound, so a resumed drain
    /// would silently drop every unapplied entry stamped above it.
    /// </summary>
    [Id(4)] public HybridLogicalClock LastAppliedHlc { get; set; }

    /// <summary>
    /// The <see cref="SnapshotStream.AsOfHlc"/> reported by the most
    /// recent <see cref="ISnapshotProvider.ExportAsync"/> call. Pinned
    /// on <see cref="IReplicationHighWaterMarkGrain.MergeBootstrapFrontierAsync"/>
    /// during <see cref="LatticeBootstrapState.IncrementalHandoff"/>.
    /// </summary>
    [Id(5)] public HybridLogicalClock SnapshotAsOfHlc { get; set; }

    /// <summary>
    /// The <see cref="SnapshotStream.CausalStableFrontier"/> reported
    /// by the most recent <see cref="ISnapshotProvider.ExportAsync"/>
    /// call. Pinned alongside <see cref="SnapshotAsOfHlc"/> during
    /// <see cref="LatticeBootstrapState.IncrementalHandoff"/>.
    /// Defaults to an empty <see cref="VersionVector"/> so the field
    /// is never <see langword="null"/> at pin time.
    /// </summary>
    [Id(6)] public VersionVector CausalStableFrontier { get; set; } = new();
}
