import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { workspaceRoot } from "./hyperframes.js";

// The docs site's design system is the single source of truth for the series:
// its palette, type and mark in docs-site/template/public/, and its join
// figures in docs-site/figures/join-figures.json, all documented in DESIGN.md
// at the repository root. Compositions are served with videos/ as their base
// URL and cannot reach docs-site/, so the parts they need are copied into
// assets/brand/site/ (ignored by git) before every preview, check and render.
// Nothing is duplicated in git, and a design change reaches the videos on the
// next run.

/** The docs site the design system is read from; VIDEOS_DOCS_SITE overrides it. */
export const defaultDocsSite = path.resolve(workspaceRoot, "..", "docs-site");

/** Where compositions read it: assets/brand/site/, which brand.css imports. */
export const defaultBrandTarget = path.join(workspaceRoot, "assets", "brand", "site");

const GENERATED = "/* Generated by videos/tools/lib/brand.js from the docs site design system. Do not edit. */\n";

/**
 * The @font-face rules of a stylesheet, with font-display forced to `block`:
 * a web page may swap a fallback face in and out, but a rendered frame must
 * never be captured in the fallback.
 */
export function fontFaces(css) {
  return (css.match(/@font-face\s*\{[^}]*\}/g) ?? []).map((block) =>
    /font-display\s*:/i.test(block)
      ? block.replace(/font-display\s*:\s*[a-z-]+/i, "font-display: block")
      : block.replace(/\s*\}$/, "\n  font-display: block;\n}"),
  );
}

/** The files a set of @font-face rules loads, relative to the stylesheet. */
export function fontSources(faces) {
  return faces.flatMap((face) => [...face.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g)].map((match) => match[1]));
}

/** The family an @font-face rule declares. */
export function faceFamily(face) {
  return /font-family\s*:\s*["']?([^"';]+?)["']?\s*;/i.exec(face)?.[1].trim();
}

/** The first family of a font-stack custom property in the site's tokens. */
export function primaryFamily(tokensCss, property) {
  const stack = new RegExp(`${property}\\s*:\\s*([^;]+);`).exec(tokensCss)?.[1];
  if (!stack) {
    throw new Error(`brand: the site tokens do not define ${property}`);
  }
  return stack.split(",")[0].trim().replace(/^["']|["']$/g, "");
}

/**
 * The camera's font stacks: the site's own self-hosted family, then only a
 * generic. The site's stacks go on to name system and web fallbacks, and the
 * renderer fetches any named family it has no @font-face for from Google
 * Fonts; a render must use the site's faces and touch no network, so the
 * fallbacks are dropped rather than resolved.
 */
export function cameraStacks(tokensCss, faces) {
  const declared = new Set(faces.map(faceFamily));
  const stacks = {};
  for (const [variable, property, generic] of [
    ["--lv-font-sans", "--lt-font-sans", "sans-serif"],
    ["--lv-font-mono", "--lt-font-mono", "monospace"],
  ]) {
    const family = primaryFamily(tokensCss, property);
    if (!declared.has(family)) {
      throw new Error(`brand: the site's ${property} leads with "${family}", which no @font-face rule in its main.css self-hosts`);
    }
    stacks[variable] = `"${family}", ${generic}`;
  }
  return stacks;
}

/**
 * The site's join-figure scenarios as a script: compositions load it before
 * any component mounts, so a figure reads its scenario synchronously rather
 * than fetching it while the renderer waits.
 */
export function joinFiguresScript(json) {
  const spec = JSON.parse(json);
  if (!Array.isArray(spec.figures) || spec.figures.length === 0) {
    throw new Error("brand: the site's join-figures.json lists no figures");
  }
  return `${GENERATED}window.LatticeJoinFigures = Object.freeze(${JSON.stringify(spec, null, 2)});\n`;
}

/** CLI commands that load compositions, and so need the design system copied in first. */
export const brandCommands = Object.freeze(
  new Set(["preview", "lint", "check", "validate", "snapshot", "render", "inspect", "keyframes", "compare", "benchmark"]),
);

/**
 * Copies the design system into the workspace: tokens.css verbatim; the
 * @font-face rules of main.css as fonts.css, followed by the camera font
 * stacks (--lv-font-sans, --lv-font-mono); the font files and their licences;
 * the mark; and the join-figure scenarios as join-figures.js. Fails loudly
 * when a part is missing, when a rule names a font file that is not there, or
 * when the site's stack leads with a family it does not self-host, rather than
 * letting a render fall back to whatever the machine or the network supplies.
 */
export function syncBrand({ docsSite = process.env.VIDEOS_DOCS_SITE || defaultDocsSite, target = defaultBrandTarget } = {}) {
  const publicDir = path.join(docsSite, "template", "public");
  const required = {
    tokens: path.join(publicDir, "tokens.css"),
    main: path.join(publicDir, "main.css"),
    mark: path.join(publicDir, "lattice-mark.svg"),
    figures: path.join(docsSite, "figures", "join-figures.json"),
  };
  for (const file of Object.values(required)) {
    if (!existsSync(file)) {
      throw new Error(
        `brand: ${file} does not exist. The series reads the docs site's design system; ` +
          "set VIDEOS_DOCS_SITE to a docs-site directory that has it.",
      );
    }
  }

  const faces = fontFaces(readFileSync(required.main, "utf8"));
  for (const file of fontSources(faces)) {
    if (!existsSync(path.join(publicDir, file))) {
      throw new Error(`brand: an @font-face rule in ${required.main} loads ${file}, which does not exist`);
    }
  }
  const tokensCss = readFileSync(required.tokens, "utf8");
  const stacks = cameraStacks(tokensCss, faces);
  const figures = joinFiguresScript(readFileSync(required.figures, "utf8"));

  rmSync(target, { recursive: true, force: true });
  mkdirSync(path.join(target, "fonts"), { recursive: true });
  writeFileSync(path.join(target, "tokens.css"), tokensCss);
  const declarations = Object.entries(stacks).map(([variable, stack]) => `  ${variable}: ${stack};`).join("\n");
  writeFileSync(path.join(target, "fonts.css"), `${GENERATED}\n${faces.join("\n\n")}\n\n:root {\n${declarations}\n}\n`);
  writeFileSync(path.join(target, "join-figures.js"), figures);
  copyFileSync(required.mark, path.join(target, "lattice-mark.svg"));

  const fontsDir = path.join(publicDir, "fonts");
  const fonts = existsSync(fontsDir) ? readdirSync(fontsDir).filter((file) => /\.(woff2|woff|txt)$/i.test(file)) : [];
  for (const file of fonts) {
    copyFileSync(path.join(fontsDir, file), path.join(target, "fonts", file));
  }
  return { docsSite, faces: faces.length, files: fonts.length };
}