#!/usr/bin/env python3
"""Guard - bucket closing list (issue #3320).

THE HALF OF THE CONVENTION THAT NOTHING CHECKED
-----------------------------------------------
The epic/bucket convention has two halves. A member pull request into an
integration branch must NOT carry a closing keyword, because GitHub honours one
only when the pull request targets the default branch - `Guard - inert closing
keywords` in ci.yml enforces that half. The other half is that the bucket's own
pull request into the default branch carries every closing reference its members
gave up, and until this guard existed nothing observed it: no test, no gate, no
report. It is also the half that actually closes the issues.

Measured on the live bucket pull request #2482: its computed closing list named
324 issues and 22 completed ones were missing, spanning every member merged
after #3252. The list did not break. It STOPPED BEING EXTENDED, and a list that
has stopped being extended renders identically to a maintained one. There is no
red, no error and no diff to notice, and the failure has no trigger of its own -
an inert closing list produces no event. That is why it is gated here rather
than reviewed by eye.

THE PREDICATE, AND WHAT IT DELIBERATELY IS NOT
----------------------------------------------
Fail when an OPEN issue claimed by a merged member pull request is absent from
the bucket pull request's COMPUTED closing set and is not explicitly held open
with a stated reason.

The obvious alternative - "every issue the members referenced is closed" - is
NOT checkable here and was rejected rather than overlooked. An artefact
generated by an action cannot be validated by a check that runs before that
action: the issues close at merge, so that predicate could never pass on an open
pull request, would block every bucket forever, and would be switched off within
a week. Every input below exists on the OPEN pull request, so this guard is
decidable now and re-decidable on every `synchronize`.

  input                              | source                  | exists
  -----------------------------------|-------------------------|-------------
  merged member PRs and their bodies | REST pulls?base=<head>  | they merged
                                     |                         | BEFORE this PR
  the bucket's closing set           | GraphQL on the PR node  | computed while
                                     | closingIssuesReferences | the PR is open
  issue-vs-PR, open-vs-closed        | REST issues/{n}         | always
  the exclusion block                | this PR's body          | now
  WHETHER THE ISSUES ACTUALLY CLOSE  | post-merge only         | NOT READ

READ THE COMPUTED SET, NEVER THE BODY TEXT
------------------------------------------
An oversized pull-request body SILENTLY TRUNCATES GitHub's closing-reference
parse to a clean prefix. Measured on this repository: a 136,402-character body
had 229 of 234 references honoured, while a 24,570-character body had all 234.
There is no error and no warning - the surplus references simply do not exist as
far as the API is concerned. A guard reading the body text and a guard reading
`closingIssuesReferences` therefore disagree on exactly the cases that matter,
and the computed set is the one that decides what happens at merge. It also
PAGES, so this reads every page rather than the first hundred.

The body IS read for the exclusion block, because that has no GitHub-computed
counterpart. The asymmetry is safe in that direction: truncation can only make
GitHub honour FEWER references (turning a pass into a failure here, which is
loud), whereas the exclusion block is read whole from the API and is a waiver a
human wrote down.

WHY IT REPORTS AND NEVER PROPOSES
---------------------------------
The two mistakes are not symmetric. A wrongly-added closing reference
auto-closes a live issue SILENTLY at merge. A missing one leaves an issue open,
which is visible and recoverable. So this guard reports a gap and requires an
explicit decision; it never proposes or applies a closure.

`Refs #N` IS NOT RELIABLY A DEFERRED CLOSURE
--------------------------------------------
Member bodies also cite issues for context - PR #2913 references five issues
including the epic itself. A guard that silently demanded closure for every
`Refs` would push maintainers toward auto-closing live issues, which is worse
than the defect it fixes. That is what the exclusion block is for, and why an
exclusion MUST carry a reason: a deliberately-held-open issue becomes a stated
decision rather than an omission, and the two stop being indistinguishable.

Run standalone (it self-reports when the pull-request shape is not a bucket):
  python3 .github/workflows/bucket-closing-list-guard.py
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

# A reason shorter than this is not a stated decision, it is a shrug. The bound
# is deliberately low: it exists to reject `- #123 -` and `- #123 - n/a`, not to
# adjudicate prose.
MIN_REASON_CHARS = 12

# Defence against a paginator that cannot terminate. Reaching either bound is
# reported as a failure rather than quietly truncating the population, because a
# truncated population and a clean one are the same string in the result.
MAX_PAGES = 100

EXCLUSION_HEADING = "Deliberately held open"


class GuardError(RuntimeError):
    """A condition under which the guard must fail rather than report clean."""


# ---------------------------------------------------------------------------
# Text
# ---------------------------------------------------------------------------

def visible_text(body: str) -> str:
    """The body with the regions GitHub does not linkify removed.

    Fenced blocks, blockquotes and inline code spans are stripped, because
    GitHub does not linkify a reference inside them and so cannot act on one.
    That matters in both directions here: a pull request DISCUSSING this trap
    contains the literal text and is entirely correct, and a member that shows
    an example reference in backticks has not claimed anything.

    This mirrors, line for line, the `honoured()` region-stripping in the
    `Guard - inert closing keywords` step of ci.yml. The duplication is
    deliberate and unavoidable rather than an oversight: that guard is an inline
    heredoc inside a YAML step, so there is no module for this one to import.
    The two are kept textually identical so a divergence is visible in a diff,
    and each carries its own planted probes so a divergence is also visible in a
    run.
    """
    out: list[str] = []
    fence: str | None = None
    for line in body.splitlines():
        stripped = line.lstrip()
        if fence is None:
            opener = re.match(r"(`{3,}|~{3,})", stripped)
            if opener:
                fence = opener.group(1)[:3]
                continue
            if stripped.startswith(">"):
                continue
            out.append(line)
        elif stripped.startswith(fence):
            fence = None
    return re.sub(r"`[^`\n]*`", "", "\n".join(out))


def _reference_pattern(repo: str) -> str:
    """`#N`, and `owner/repo#N` for THIS repository only.

    A cross-repository reference is out of scope and is deliberately not
    matched: this guard reconciles against a closing set scoped to one
    repository, and silently importing a foreign issue number into that
    comparison would manufacture gaps that cannot be closed here.
    """
    return rf"(?:{re.escape(repo)})?#(\d+)"


def claimed_issues(body: str, repo: str) -> set[int]:
    """Every number a member body claims with `Refs`.

    Accepts `Refs #1`, `Ref: #1` and the comma continuation `Refs #1, #2, #3`,
    which is how a member citing several items actually writes it.
    """
    text = visible_text(body)
    pattern = _reference_pattern(repo)
    run = rf"{pattern}(?:[ \t]*,[ \t]*{pattern})*"
    found: set[int] = set()
    for match in re.finditer(rf"(?i)\brefs?\b[ \t]*:?[ \t]*({run})", text):
        found.update(int(n) for n in re.findall(r"#(\d+)", match.group(1)))
    return found


def parse_exclusions(body: str) -> tuple[dict[int, str], list[str]]:
    """The `## Deliberately held open` section: (issue -> reason, malformed).

    The section runs from its heading to the next heading of the same or a
    higher level, or to the end of the body. Any line inside it that names an
    issue must also state a reason; one that does not is returned as malformed
    and fails the guard. An exclusion without a reason would be exactly the
    silent waiver this guard exists to abolish, so it is never treated as one.
    """
    lines = visible_text(body).splitlines()
    start = None
    level = 0
    for index, line in enumerate(lines):
        heading = re.match(rf"(?i)^(#{{1,6}})[ \t]*{EXCLUSION_HEADING}[ \t]*:?[ \t]*$",
                           line.strip())
        if heading:
            start = index + 1
            level = len(heading.group(1))
            break
    if start is None:
        return {}, []

    excluded: dict[int, str] = {}
    malformed: list[str] = []
    for line in lines[start:]:
        closing = re.match(r"^(#{1,6})[ \t]", line.strip() + " ")
        if closing and len(closing.group(1)) <= level:
            break
        if not re.search(r"#\d+", line):
            continue
        entry = re.match(
            r"^[ \t]*(?:[-*+][ \t]*)?\|?[ \t]*#(\d+)[ \t]*(?:\||-+|:)[ \t]*(.*?)[ \t]*$",
            line)
        reason = re.sub(r"\|[ \t]*$", "", entry.group(2)).strip() if entry else ""
        if entry and len(re.sub(r"\s", "", reason)) >= MIN_REASON_CHARS:
            excluded[int(entry.group(1))] = reason
        else:
            malformed.append(line.strip())
    return excluded, malformed


def reconcile(claims: dict[int, list[int]], closing: set[int],
              excluded: set[int]) -> list[int]:
    """Claimed numbers the bucket neither closes nor explicitly holds open.

    Pure, so it can be driven over planted inputs by the anti-vacuity control
    below. Classification (issue versus pull request, open versus closed) is
    applied to this result rather than folded in here, so that the expensive
    per-number API calls are made only for candidates that could actually fail.
    """
    return sorted(n for n in claims if n not in closing and n not in excluded)


# ---------------------------------------------------------------------------
# GitHub
# ---------------------------------------------------------------------------

def _request(url: str, *, payload: dict | None = None) -> object:
    request = urllib.request.Request(url, method="POST" if payload else "GET")
    request.add_header("Accept", "application/vnd.github+json")
    token = os.environ.get("GITHUB_TOKEN", "")
    if token:
        request.add_header("Authorization", "Bearer " + token)
    data = None
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        request.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(request, data, timeout=60) as response:
            raw = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise GuardError(f"{url} returned HTTP {error.code}: "
                         f"{error.read().decode('utf-8', 'replace')[:400]}") from error
    except OSError as error:
        raise GuardError(f"{url} could not be reached: {error}") from error
    return json.loads(raw) if raw else None


def merged_members(api: str, repo: str, head_ref: str) -> list[dict]:
    """Every merged pull request whose base is this bucket's head branch."""
    members: list[dict] = []
    for page in range(1, MAX_PAGES + 1):
        query = urllib.parse.urlencode(
            {"state": "closed", "base": head_ref, "per_page": 100, "page": page})
        batch = _request(f"{api}/repos/{repo}/pulls?{query}")
        if not isinstance(batch, list):
            raise GuardError("the member-discovery call did not return a list, so the "
                             "population this guard reconciles against was never read.")
        members.extend(pr for pr in batch if pr.get("merged_at"))
        if len(batch) < 100:
            return members
    raise GuardError(f"member discovery did not terminate within {MAX_PAGES} pages.")


CLOSING_QUERY = """
query($owner:String!,$name:String!,$number:Int!,$cursor:String){
  repository(owner:$owner,name:$name){
    pullRequest(number:$number){
      closingIssuesReferences(first:100, after:$cursor){
        pageInfo{ hasNextPage endCursor }
        nodes{ number }
      }
    }
  }
}
"""


def closing_set(graphql: str, owner: str, name: str, number: int) -> set[int]:
    """The references GitHub itself computed for this pull request, ALL pages.

    Reading only the first page would cap the set at 100 and manufacture gaps
    on precisely the large buckets this guard exists for - the live one carried
    324.
    """
    found: set[int] = set()
    cursor = None
    for _ in range(MAX_PAGES):
        payload = {"query": CLOSING_QUERY,
                   "variables": {"owner": owner, "name": name,
                                 "number": number, "cursor": cursor}}
        body = _request(graphql, payload=payload)
        if not isinstance(body, dict) or body.get("errors"):
            raise GuardError("the closing-set query failed: " + json.dumps(body)[:400])
        pull = (((body.get("data") or {}).get("repository") or {}).get("pullRequest"))
        if not pull:
            raise GuardError("the closing-set query returned no pull request, so the "
                             "set this guard reconciles against was never read.")
        block = pull.get("closingIssuesReferences") or {}
        found.update(node["number"] for node in block.get("nodes") or [])
        info = block.get("pageInfo") or {}
        if not info.get("hasNextPage"):
            return found
        cursor = info.get("endCursor")
    raise GuardError(f"the closing set did not paginate to an end within {MAX_PAGES} pages.")


def classify(api: str, repo: str, number: int) -> str:
    """`PR`, `OPEN`, `CLOSED` or `MISSING` for one number.

    Issue numbers and pull-request numbers share ONE sequence, so a `Refs #N`
    may well name a pull request. Demanding that a pull request be closed by the
    bucket would be incoherent, so it is classified out rather than reported.
    """
    item = _request(f"{api}/repos/{repo}/issues/{number}")
    if item is None:
        return "MISSING"
    if not isinstance(item, dict):
        raise GuardError(f"classifying #{number} returned an unexpected shape.")
    if item.get("pull_request"):
        return "PR"
    return "OPEN" if item.get("state") == "open" else "CLOSED"


# ---------------------------------------------------------------------------
# Anti-vacuity controls
# ---------------------------------------------------------------------------

def self_test() -> None:
    """Prove the extractor, the exclusion parser and the reconciler still work.

    A silent pass is this guard's desired outcome, so a guard whose parts have
    quietly stopped discriminating looks exactly like a correctly-maintained
    bucket. These planted controls make that state observable on every run,
    before any network call is made. Shipping a guard that could certify an
    empty population would be self-refuting on an issue about exactly that.

    There is one control per region the predicate claims to strip, not one per
    region that is convenient to write inline - with any single arm of
    visible_text() disabled the remaining probes still pass unanimously, so a
    third of the predicate could break undetected without all of them.
    """
    repo = "o/r"
    probes: list[tuple[str, set[int]]] = [
        ("Refs #1", {1}),
        ("Refs: #1", {1}),
        ("Refs #1, #2, #3", {1, 2, 3}),
        ("Refs o/r#4", {4}),
        ("`Refs #1`", set()),
        ("> Refs #1", set()),
        ("```\nRefs #1\n```", set()),
        ("mentions #1 without the keyword", set()),
    ]
    broken = [text for text, want in probes if claimed_issues(text, repo) != want]
    if broken:
        raise GuardError(
            "this guard's own reference extractor is broken - it failed its planted "
            f"self-test on: {broken!r}. Until that is fixed the guard cannot detect "
            "anything, and a pass from it means nothing.")

    good = "## Deliberately held open\n\n- #7 - a properly stated reason here\n"
    bad = "## Deliberately held open\n\n- #7 -\n"
    ends = "## Deliberately held open\n\n- #7 - a properly stated reason here\n## Next\n\n- #8 - ignored\n"
    if parse_exclusions(good) != ({7: "a properly stated reason here"}, []):
        raise GuardError("this guard's exclusion parser no longer reads a well-formed "
                         "exclusion, so every exclusion would be ignored.")
    if parse_exclusions(bad)[1] == []:
        raise GuardError("this guard's exclusion parser no longer rejects a reasonless "
                         "exclusion, so a silent waiver would pass as a stated decision - "
                         "the exact failure it exists to prevent.")
    if 8 in parse_exclusions(ends)[0]:
        raise GuardError("this guard's exclusion parser runs past the end of its own "
                         "section, so unrelated issue numbers would be waived.")
    if parse_exclusions("no section here at all\n\n- #7 - nope") != ({}, []):
        raise GuardError("this guard's exclusion parser matches outside its section.")

    # The probes above prove the parts discriminate. They cannot prove anything
    # still CALLS the reconciler with them. This control drives the real
    # reconciler over a planted gap, so an arm that has stopped reporting is
    # caught even while every predicate is perfectly healthy.
    planted = reconcile({101: [1], 102: [1], 103: [1]}, {102}, {103})
    if planted != [101]:
        raise GuardError(
            "this guard's reconciler is broken: over a planted claim set with one "
            f"gap it reported {planted!r} rather than [101]. Until that is fixed a "
            "pass from it is not evidence of a complete closing list.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    try:
        self_test()
    except GuardError as error:
        print(f"::error::{error}")
        return 1

    base_ref = os.environ.get("BASE_REF", "")
    head_ref = os.environ.get("HEAD_REF", "")
    default_branch = os.environ.get("DEFAULT_BRANCH", "")

    # Mirrors the step's own `if:` condition. Kept here as well so the shape
    # rule is executable and testable rather than only expressible in YAML, and
    # so running this script by hand on the wrong pull request says so.
    if not default_branch or base_ref != default_branch or "/epic/" not in head_ref:
        print(f"OK (not applicable): this guard reconciles a BUCKET pull request - base "
              f"'{default_branch}', head matching '*/epic/**'. This one is base "
              f"'{base_ref}', head '{head_ref}', so there is no closing list to check. "
              "The member half is gated separately by 'Guard - inert closing keywords'.")
        return 0

    repo = os.environ.get("GITHUB_REPOSITORY", "")
    api = (os.environ.get("GITHUB_API_URL") or "https://api.github.com").rstrip("/")
    graphql = os.environ.get("GITHUB_GRAPHQL_URL") or "https://api.github.com/graphql"
    body = os.environ.get("PR_BODY") or ""
    try:
        number = int(os.environ.get("PR_NUMBER") or "0")
    except ValueError:
        number = 0
    if "/" not in repo or number <= 0:
        print("::error::This guard was given no repository or pull-request number, so it "
              "read nothing. That is failed rather than passed deliberately: an unread "
              "population and a complete one are indistinguishable in the result.")
        return 1
    owner, name = repo.split("/", 1)

    try:
        members = merged_members(api, repo, head_ref)
        if not members:
            print(f"::error::NON-VACUITY: no MERGED pull request has base '{head_ref}', so "
                  "this guard reconciled the bucket's closing list against an empty "
                  "population and would have certified any list whatsoever. That is "
                  "failed rather than passed, because silently certifying an empty "
                  "population is the defect class this gate exists to catch (#3320). A "
                  "bucket pull request raised before its first member merges will clear "
                  "this as soon as one does - the check re-runs on every push to the "
                  "branch.")
            return 1

        claims: dict[int, list[int]] = {}
        for member in members:
            for issue in claimed_issues(member.get("body") or "", repo):
                claims.setdefault(issue, []).append(member["number"])
        if not claims:
            print(f"::error::NON-VACUITY: {len(members)} merged member pull request(s) were "
                  f"read and NOT ONE carries a 'Refs #N' reference, so there is nothing to "
                  "reconcile and this guard would pass over any closing list at all. Member "
                  "pull requests give up their closing keyword and record the deferral as "
                  "'Refs #N'; a bucket whose members record nothing cannot be checked, so "
                  "this is reported as a failure rather than as a clean result.")
            return 1

        excluded, malformed = parse_exclusions(body)
        if malformed:
            print(f"::error::The '{EXCLUSION_HEADING}' section names an issue without "
                  "stating a reason, on: " + "; ".join(repr(x) for x in malformed) +
                  ". An exclusion exists precisely to turn an omission into a stated "
                  "decision, so a reasonless one is rejected rather than honoured. Write "
                  f"'- #N - why it stays open' (at least {MIN_REASON_CHARS} characters).")
            return 1

        closing = closing_set(graphql, owner, name, number)
        if not closing:
            print(f"::error::NON-VACUITY: {len(claims)} issue(s) are claimed by a merged "
                  "member, but this pull request's computed closing set came back EMPTY. "
                  "That is reported separately from an ordinary gap because the two have "
                  "different causes and different fixes: a partial list means some "
                  "references were not carried over, whereas a wholly empty one usually "
                  "means the read itself stopped working - a changed GraphQL field, a "
                  "missing 'pull-requests: read' scope, or a body whose references GitHub "
                  "never parsed. Check the set directly with: gh pr view <n> --json "
                  "closingIssuesReferences. If it really is empty, this pull request "
                  "currently closes nothing at all and every claimed issue would be left "
                  "open by a merge.")
            return 1

        candidates = reconcile(claims, closing, set(excluded))

        gaps: list[int] = []
        dropped: dict[str, list[int]] = {"PR": [], "CLOSED": [], "MISSING": []}
        for candidate in candidates:
            if candidate == number:
                continue
            verdict = classify(api, repo, candidate)
            if verdict == "OPEN":
                gaps.append(candidate)
            else:
                dropped[verdict].append(candidate)
    except GuardError as error:
        print(f"::error::This guard could not read what it reconciles ({error}). That is "
              "failed rather than passed deliberately: a population it could not look at "
              "and a clean one are the same result, and reporting the first as the second "
              "is the defect this gate exists to prevent.")
        return 1

    summary = (f"{len(members)} merged member pull request(s), {len(claims)} issue(s) "
               f"claimed by 'Refs', {len(closing)} in the computed closing set, "
               f"{len(excluded)} explicitly held open")
    for kind, label in (("PR", "name a pull request, not an issue"),
                        ("CLOSED", "are already closed"),
                        ("MISSING", "do not resolve")):
        if dropped[kind]:
            print(f"::notice::Not required: "
                  + ", ".join(f"#{n}" for n in dropped[kind]) + f" {label}.")
    stale = sorted(n for n in excluded if n in closing)
    if stale:
        print("::notice::Stale exclusion(s): " + ", ".join(f"#{n}" for n in stale) +
              " are held open in the body but ARE in the closing set. Harmless, and "
              "reported rather than failed so an exclusion can outlive a rebase.")

    if not gaps:
        print(f"OK: self-tests passed; {summary}; every claimed open issue is either in "
              "the closing set or explicitly held open with a reason.")
        return 0

    print("::error::BUCKET CLOSING LIST INCOMPLETE. " + summary + ". These OPEN issues "
          "were claimed by a merged member and are neither in this pull request's "
          "computed closing set nor explicitly held open:")
    for gap in gaps:
        claimed_by = ", ".join(f"#{m}" for m in sorted(claims[gap]))
        print(f"::error::  #{gap} - claimed by merged member pull request(s) {claimed_by}")
    print("::error::Each member gave up its own closing keyword because GitHub honours "
          "one only on the default branch, so this pull request is the only place the "
          "closure can happen. Either add the closing reference here, or record the "
          f"decision under a '## {EXCLUSION_HEADING}' heading as '- #N - why'. Verify "
          "with: gh pr view <n> --json closingIssuesReferences (the computed set, not "
          "the body - an oversized body truncates GitHub's parse silently).")
    return 1


if __name__ == "__main__":
    sys.exit(main())
